package com.dicoding.submission.mybestbook;

import java.util.ArrayList;

public class BooksData {
    private static String[][] data = new String[][] {
            {"Bumi Manusia", "Pramoedya A. Toer", "Bumi Manusia merupakan buku pertama dari tetralogi Buku karya Pramoedya Ananta Noer. Novel bergenre sejarah ini berlatarkan akhir abad ke 19 di Blora. Menceritakan tentang Minke, seorang pribumi yang terpelajar, gigih, dan berani untuk mengejar apa yang diimpikannya. Ia bersekolah di H.B.S. Surabaya di tengah-tengah orang Eropa yang sering mengejeknya karena ia seorang pribumi. Bergaul dengan orang Eropa membuatnya mengagungkan budaya Eropa, sehingga melupakan budayanya sendiri. Hal tersebut lalu membuatnya ingin mencari jati dirinya.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-1548731730337.jpg", "https://cdn.gramedia.com/uploads/authors/pramoedya-ananta-toer-copy__w200_hauto.jpg"},
            {"Laskar Pelangi", "Andrea Hirata", "Berlatarkan pedesaan di dekat pantai di Belitung, novel Laskar Pelangi menceritakan tentang sebelas anak dari keluarga miskin yang bersekolah di SD Muhammadiyah Belitung. Kondisi yang miskin dan serba kekurangan tidak membuat semangat mereka untuk meraih hidup yang lebih baik surut. Justru hal tersebut memotivasi mereka untuk terus bersekolah, meski sekolah mereka hampir ditutup karena kekurangan murid. Kesetiakawanan, kegigihan, dan pantang menyerah yang digambarkan tokoh anak-anak di dalam novel ini menjadi pesan moral yang sangat baik untuk diajarkan kepada anak-anak kita. Meski keadaan susah, kita harus berusaha keras untuk bisa bertahan dan mendapatkan hidup yang lebih baik.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317304572.jpg", "https://cdn.gramedia.com/uploads/authors/hirata_-_mr_andrea_hirata_-_photo_from_him_27march15__w200_hauto.jpg"},
            {"Anak Semua Bangsa", "Pramoedya A. Toer", "Lanjutan dari Bumi Manusia, novel Anak Semua Bangsa masih bercerita tentang Minke tapi lebih menceritakan tentang kondisi negara Indonesia di tahun 1898-1918. Semasa penjajahan Hindia Belanda, rakyat Indonesia mengalami penderitaan. Mereka ditindas, diteror, dan dipaksa untuk memberikan tanahnya kepada bangsa Belanda. Penderitaan rakyat semakin lengkap dengan sewenang-wenangnya para pejabat, baik Eropa maupun pribumi. Mereka merampas apa yang mereka mau dari rakyat. Selain merampas kemerdekaan, mereka juga merampas tanah, harta, benda, dan bahkan anak serta istri pun dapat mereka rampas. Anak Semua Bangsa merupakan periode observasi Minke untuk mencari spirit lapangan dan kehidupan arus bawah pribumi yang tak berdaya melawan kekuasaan dan kekuatan Eropa.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-1548731730585.jpg", "https://cdn.gramedia.com/uploads/authors/pramoedya-ananta-toer-copy__w200_hauto.jpg"},
            {"Ronggeng Dukuh Paruk", "Ahmad Tohari", "Dukuh Paruk merupakan sebuah desa kecil yang terpencil dan miskin. Meski begitu, warga di sana memiliki sebuah warisan kesenian ronggeng yang menjadi kebanggaan dan selalu menghidupkan gairah mereka. Suatu ketika, terjadi musibah keracunan tempe bongkrek yang menewaskan belasan penduduk di sana, hingga lenyaplah gairah hidup masyarakatnya. Semangat hidup mereka muncul lagi saat seorang gadis muda bernama Srintil memperlihatkan bakatnya dalam menari ronggeng. Kelihaiannya itu kemudian diakui oleh semua warga Dukuh Paruk dan membuatnya jadi gadis milik orang banyak. Hal tersebut membuatnya harus berpisah dengan sang kekasih dan memberikan luka mendalam di hatinya.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317307146.jpg", "https://cdn.gramedia.com/uploads/authors/ahmad_tohari__w200_hauto.jpg"},
            {"Saman", "Ayu Utami", "Tokoh utama di novel Saman bernama Wisanggeni atau yang sering dipanggil Wis. Wis merupakan seorang anak yang mengikuti ayahnya pindah kerja dari Yogyakarta ke Prabumulih. Selesai menamatkan gelar sarjana teologinya di Institut Pertanian Bogor, ia menjadi seorang Pastor dan mendapatkan julukan Romo Wis. Saat dipindahkan ke Prabumulih, ia melihat sudah banyak perubahan yang terjadi di sana. Perjuangannya untuk membantu seorang gadis cacat bernama Upi membuatnya harus menerima banyak cobaan. Hingga akhirnya ia berganti nama menjadi Saman dan memutuskan untuk pindah ke New York dan kini menjadi aktivis perburuhan dan menjalani LSM.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317309061.jpg", "https://cdn.gramedia.com/uploads/authors/Ayu-Utami__w200_hauto.jpg"},
            {"5 cm", "Donny Dhirgantoro", "Menjadi buku terlaris di Gramedia Bookstore selama dua tahun berturut-turut, novel 5 Cm tentunya harus masuk dalam daftar novel Indonesia wajib dibaca. Novel yang ditulis oleh Donny Dhirgantoro ini menceritakan tentang kehidupan lima sahabat yang telah berteman selama tujuh tahun. Mereka telah mencoba berbagai hal, seperti mengunjungi kafe paling terkenal di Jakarta sampai menonton layar tancap. Sampai suatu hari, mereka melakukan sebuah perjalanan yang mengisi hidup mereka dengan keyakinan, mimpi, cita-cita, dan cinta.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317311094.jpg", "https://cdn.gramedia.com/uploads/authors/Donny_Dhirgantoro__w200_hauto.jpg"},
            {"Negeri 5 Menara", "A. Fuadi", "Novel yang terinspirasi dari kisah nyata memang selalu menarik untuk dibaca sperti novel Negeri 5 Menara. Sebuah novel karangan Ahmad Fuadi ini merupakan buku pertama dari trilogi Negeri 5 Menara yang mengisahkan tentang enam orang santri dari enam daerah berbeda yang menuntut ilmu di Pondok Madani, Jawa Timur. Meski jauh dari rumah, tapi mereka berhasil mewujudkan mimpi menggapai jendela dunia. Alif sebagai tokoh utama dalam novel ini suka nongkrong di bawah menara Pondok Madani bersama kelima temannya. Mereka berenam kerap menunggu magrib sambil menatap awan lembayung yang berarak pulang ke ufuk. Di mata belia mereka, awan-awan itu menjelma menjadi negara dan benua impian masing-masing. Mereka tidak tahu ke mana impian jiwa muda ini membawa mereka. Yang mereka tahu adalah jangan pernah meremehkan impian, walau setinggi apapun karena Tuhan sungguh Maha Mendengar.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317312594.jpg", "https://cdn.gramedia.com/uploads/authors/Fuadi-twitter_GlGjsA7__w200_hauto.jpg"},
            {"Sang Pemimpi", "Andrea Hirata", "Merupakan buku kedua dari tetralogi Laskar Pelangi, novel Sang Pemimpi menceritakan tentang hubungan persahabatan Ikal dan Arai serta kekuatan mimpi mereka untuk bisa menuntut ilmu di Perancis. Melalui buku ini, Andrea Hirata ingin mengenalkan para pembacanya tentang arti perjuangan hidup. Ia ingin kita percaya akan tenaga cinta, kekuatan mimpi, dan pengorbanan. Bahwa dengan itu semua, kita bisa meraih apa yang diinginkan. Sangat pantas lah kalau novel ini menjadi bacaan yang wajib dibaca.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317313815.jpg", "https://cdn.gramedia.com/uploads/authors/hirata_-_mr_andrea_hirata_-_photo_from_him_27march15__w200_hauto.jpg"},
            {"Arus Balik", "Pramoedya A. Toer", "Novel Arus Balik merupakan sebuah buku sejarah yang mengisahkan tentang keadaan negara Indonesia pasca runtuhnya kerajaan Majapahit. Gaya bahasa yang digunakan oleh Pramoedya membuat kita akan mudah mengetahui pola pikir, kebudayaan, perjuangan masyarakat Nusantara saat itu. Nusantara yang awalnya berjaya harus menerima fakta bahwa arus telah berbalik dan berabad lamanya mereka terjajah. Diceritakan Wiranggaleng (Galeng) sebagai tokoh utama di dalam novel ini. Ia adalah seorang pemuda desa yang memiliki kecerdasan, keberanian, dan ketangkasan dibanding pemuda desa lainnya. Kisahnya dimulai saat Galeng mengikuti sebuah kejuaraan di Tuban bersama kekasihnya, Idayu. Kejuaraan tersebut mengantarkannya menjadi seorang pemenang yang sekaligus menjadi titik awal dari pergulatannya. Muncul berbagai macam konflik, seperti kehidupan feodalis, penjilat-penjilat, serta pengkhianatan yang menambah konflik pada kerajaan Tuban. Kemudian muncullah kerajaan Portugis yang menguasai Raja Malaka hingga Galeng diangkat sebagai duta Tuban.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-15487317314908.jpg", "https://cdn.gramedia.com/uploads/authors/pramoedya-ananta-toer-copy__w200_hauto.jpg"},
            {"Muhammad : Lelaki Penggenggam Hujan", "Tasaro G.K.", "Sebuah novel biografi berjudul Muhammad: Lelaki Penggenggam Hujan mengisahkan tentang kisah Nabi Muhammad SAW beserta para sahabatnya. Oleh Tasaro kamu akan dibawa untuk membayangkan kehidupan saat Rasulullah menyebarkan Islam. Dimulai pada saat beliau mendapatkan risalahnya di usia 40 tahun, kemudian perjuangannya untuk membawa ajaran kebenaran sesuai yang tertulis di Al Qur’an. Di rentang waktu yang sama juga diceritakan kisah seorang pemuda yang dijuluki Pemindai Surga yang berasal dari Kerajaan Persia yang bernama Kashva. Ia melakukan perjalanan untuk menelusuri tentang ramalan dari kitab suci beberapa agama. Dalam ramalan disebutkan tentang kelahiran seorang nabi akhir zaman yang akan membawa kedamaian di bumi yang ia juluki Lelaki Penggenggam Hujan. Di novel ini kita akan mengetahui bagaimana kehidupan di abad ke 6 Masehi yang ternyata tidak jauh berbeda dengan sekarang.", "https://s3-ap-southeast-1.amazonaws.com/asset1.gotomalls.com/uploads/media/images/article/M3z42Nt5IR8uavq2/article_content_image/img-M3z42Nt5IR8uavq2-d-med-1548731731671.jpg", "http://1.bp.blogspot.com/--whb1KaSum4/UtClItnxTZI/AAAAAAAAAL8/njhmkvP3QZ8/s1600/tasaro2.jpg"}
    };

    public static ArrayList<Book> getListData() {
        ArrayList<Book> list = new ArrayList<>();
        for (String[] aData : data) {
            Book book = new Book();
            book.setName(aData[0]);
            book.setAuthor(aData[1]);
            book.setSinopsis(aData[2]);
            book.setPhoto(aData[3]);
            book.setAuthorPhoto(aData[4]);

            list.add(book);
        }

        return list;
    }
}
